Skylounge Update
## SkyLounge Input Summary 
The following inputs were used by SkyLounge to generate this pull request. Changes are compared against the current workflows in the repository. 

* **[skylounge.yml](https://github.com/sky-lounge/hello/blob/3e125735a4a367b7ff80d66458b6c0804c65feb7/skylounge.yml)** (updated)

* [Lifecycle Blueprint](https://github.com/sky-lounge/skylounge-definitions/blob/b8eb82682ee6a26afee1ddcc77fc276b05d96df9/blueprints/hello-world/blueprint.yml)

#### Workflows 

* **[build-deploy](https://github.com/sky-lounge/skylounge-definitions/blob/b8eb82682ee6a26afee1ddcc77fc276b05d96df9/blueprints/hello-world/build-deploy.yml)** (updated)
  * **[integration-test](https://github.com/sky-lounge/hello/blob/3e125735a4a367b7ff80d66458b6c0804c65feb7/skylounge/jobs/integration-test.yml)** (new)
  * [build-container-image](https://github.com/sky-lounge/skylounge-definitions/blob/b8eb82682ee6a26afee1ddcc77fc276b05d96df9/step-templates/docker/build-steps.yml)

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -80,3 +80,19 @@ jobs:
         echo "$URL"
       env:
         URL: "${{ steps.deploy.outputs.url }}"
+  integration-test:
+    needs: deploy
+    name: Integration Test
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout branch
+      uses: actions/checkout@v3
+    - name: Verify index page
+      run: |
+        set -ex
+        status_code=$(curl -L -o /dev/null -s -w "%{http_code}" ${APP_URL})
+        [[ 200 -eq $status_code ]] || (echo "CURL FAILED to return 200 status" && exit 1)
+        response=$(curl -L ${APP_URL})
+        [[ $response == *"Better Automation for Software Organizations"* ]] || (echo "CURL FAILED to return result containing substring: Better Automation for Software Organizations" && exit 1)
+      env:
+        APP_URL: "${{ needs.jobs.deploy.outputs.app_url }}"
